# Generated by Django 4.0.6 on 2022-07-19 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morgue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='corpse',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morgue.gender'),
        ),
    ]
