# Generated by Django 4.0.6 on 2022-07-19 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgue', '0002_gender_alter_corpse_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpse',
            old_name='Date_of_admission',
            new_name='date_of_admission',
        ),
        migrations.RemoveField(
            model_name='corpse',
            name='Date_of_death',
        ),
        migrations.RemoveField(
            model_name='corpse',
            name='Time_of_admission',
        ),
        migrations.AddField(
            model_name='corpse',
            name='date_of_death',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 19, 11, 0, 47, 728036)),
        ),
        migrations.AddField(
            model_name='corpse',
            name='next_of_kin_contact',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='corpse',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='corpse',
            name='time_of_admission',
            field=models.TimeField(default=datetime.datetime(2022, 7, 19, 11, 0, 47, 728036)),
        ),
    ]
