# Generated by Django 4.0.6 on 2022-07-19 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morgue', '0003_rename_date_of_admission_corpse_date_of_admission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care_takers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Next_of_kin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='corpse',
            name='next_of_kin_contact',
        ),
        migrations.RemoveField(
            model_name='corpse',
            name='next_of_kin_name',
        ),
        migrations.AlterField(
            model_name='corpse',
            name='date_of_death',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 19, 17, 24, 0, 216124)),
        ),
        migrations.AlterField(
            model_name='corpse',
            name='time_of_admission',
            field=models.TimeField(default=datetime.datetime(2022, 7, 19, 17, 24, 0, 216124)),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=50)),
                ('care_taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morgue.care_takers')),
            ],
        ),
        migrations.AddField(
            model_name='corpse',
            name='next_of_kin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='morgue.next_of_kin'),
        ),
        migrations.AddField(
            model_name='corpse',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='morgue.room'),
        ),
    ]
