# Generated by Django 4.0.6 on 2022-07-19 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morgue', '0004_care_takers_next_of_kin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpse',
            name='date_of_death',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 19, 17, 25, 21, 611170)),
        ),
        migrations.AlterField(
            model_name='corpse',
            name='time_of_admission',
            field=models.TimeField(default=datetime.datetime(2022, 7, 19, 17, 25, 21, 611170)),
        ),
    ]
