# Generated by Django 4.0.6 on 2022-07-19 14:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morgue', '0005_alter_corpse_date_of_death_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care_taker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.PositiveIntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='next_of_kin',
            name='phone',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='corpse',
            name='date_of_death',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 19, 17, 52, 21, 721500)),
        ),
        migrations.AlterField(
            model_name='corpse',
            name='time_of_admission',
            field=models.TimeField(default=datetime.datetime(2022, 7, 19, 17, 52, 21, 722499)),
        ),
        migrations.AlterField(
            model_name='room',
            name='care_taker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morgue.care_taker'),
        ),
        migrations.DeleteModel(
            name='Care_takers',
        ),
    ]
