# Generated by Django 4.0.6 on 2022-08-19 08:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morgue', '0007_alter_corpse_date_of_death_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfCorpse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip', models.CharField(max_length=100)),
                ('regular', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='no_of_shelves',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corpse',
            name='date_of_death',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 19, 11, 57, 25, 812401)),
        ),
        migrations.AddField(
            model_name='corpse',
            name='type_of_corpse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='morgue.typeofcorpse'),
        ),
    ]
